project:
  type: website
  output-dir: docs

website:
  title: "ETF2121/5912 - S2 2024"
  description: "Homepage for ETF2121/5921 - Data Analysis in Business at Monash University, S2 2023."
  site-url: "https://etf2121.github.io/main"
  back-to-top-navigation: true

  open-graph: true

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Dr. Joan Tan"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Course structure
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
      - section: "Weekly Schedule"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"
          - href: weeks/week-2.qmd
            text: "Week 2"
          - href: weeks/week-3.qmd
            text: "Week 3"
          - href: weeks/week-4.qmd
            text: "Week 4"
          - href: weeks/week-5.qmd
            text: "Week 5"
          - href: weeks/week-6.qmd
            text: "Week 6"
          - href: weeks/week-7.qmd
            text: "Week 7"
          - href: weeks/week-8.qmd
            text: "Week 8"
          - href: weeks/week-9.qmd
            text: "Week 9"
          - href: weeks/week-10.qmd
            text: "Week 10"
          - href: weeks/week-11.qmd
            text: "Week 11"
          - href: weeks/week-12.qmd
            text: "Week 12"
      - section: "Assessment"
        contents:
          - href: hw/hw-1.qmd
            text: "Individual Assignment"
          - href: hw/hw-2.qmd
            text: "Group Assignment"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

execute:
  freeze: auto

editor: visual