---
title: "ETF2121/5912: Data Analysis in Business"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
---

This page provides a comprehensive outline of the topics, content, and assignments planned for the semester. Please note that this schedule is subject to updates as the semester progresses. Any changes or adjustments will be documented here to ensure you have the most current information available. In the event of any discrepancies between the information on this website and the exam timetable or course handbook, the exam timetable and course handbook will serve as the authoritative sources.

+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
| Week                      | Date              | Topic                                                          | Prepare                                                                                          | Slides                                                                                                                                                                   | Quiz/Assignments                                                | Reading                                      |
+:=========================:+===================+================================================================+:================================================================================================:+:========================================================================================================================================================================:+:===============================================================:+==============================================+
| [1](/weeks/week-1.html)   | Tue, Jul 23       | Business Analytics & Database Management System                | [📖](/labs/lab-1.html)                                                                           | [📋](https://learning.monash.edu/pluginfile.php/3800248/mod_resource/content/1/lec-1.html)                                                                               | [📝](https://learning.monash.edu/mod/quiz/view.php?id=2893140)  | 📕 Camm 1.1, 1.2, 1.3 and 1.5                |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
| [2](/weeks/week-2.html)   | Tue, Jul 30       | Database Query Language: SQL                                   | [📖](https://learning.monash.edu/pluginfile.php/3937376/mod_resource/content/2/lab-2.html)       | [📋](https://learning.monash.edu/pluginfile.php/3937400/mod_resource/content/1/lec-2.html)                                                                               | [📝](https://learning.monash.edu/mod/quiz/view.php?id=2893560)  | [✍️](/hw/hw-1.html) \| \| \| \| \|           |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
| [3](/weeks/week-3.html)   | Tue, Aug 6        | Data Wrangling                                                 | [📖](https://learning.monash.edu/pluginfile.php/3977906/mod_resource/content/3/lab-3.html)       | [📋](https://learning.monash.edu/pluginfile.php/3977860/mod_resource/content/1/lec-3.html)                                                                               | [📝](https://learning.monash.edu/mod/quiz/view.php?id=2989083)  |                                              |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
| [4](/weeks/week-4.html)   | Tue, Aug 13       | Data Visualization                                             | [📖](https://learning.monash.edu/pluginfile.php/4021915/mod_resource/content/1/lab-4.html)       | [📋](https://learning.monash.edu/pluginfile.php/4022053/mod_resource/content/1/lec-4.html)                                                                               | [📝](https://learning.monash.edu/mod/quiz/view.php?id=29897713) | 📕 Camm 3.1, 3.2, 3.6                        |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
| [5](/weeks/week-5.html)   | Tue, Aug 20       | Descriptive Statistics                                         | [📖](https://learning.monash.edu/pluginfile.php/4038700/mod_resource/content/1/lab-5.html)       | [📋](https://learning.monash.edu/pluginfile.php/4038721/mod_resource/content/1/lec-5.html#/title-slide) [📋](https://learning.monash.edu/mod/folder/view.php?id=3063771) | [📝](https://learning.monash.edu/mod/quiz/view.php?id=3059917)  | 📕 Camm Chapter 2                            |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
| [6](/weeks/week-6.html)   | Tue, Aug 27       | Probability: An Introduction to Modelling Uncertainty          | [📖](https://learning.monash.edu/mod/folder/view.php?id=3072768)                                 | [📋](https://learning.monash.edu/pluginfile.php/4053136/mod_resource/content/1/lec-6.html#/title-slide)                                                                  | [📝](https://learning.monash.edu/mod/quiz/view.php?id=3072191)  | 📕 Camm Chapter 5                            |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
| [7](/weeks/week-7.html)   | Tue, Sep 3        | Descriptive Analytics: Clustering                              | [📖](https://learning.monash.edu/mod/folder/view.php?id=3096615)                                 | [📋](https://learning.monash.edu/pluginfile.php/4081279/mod_resource/content/1/lec-7.html#/title-slide)                                                                  | [📝](https://learning.monash.edu/mod/quiz/view.php?id=3096610)  | 📕 Camm Chapter 6.2                          |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
|                           | *Wed, Sep 4*      | *Individual assignment submission deadline*                    |                                                                                                  |                                                                                                                                                                          |                                                                 |                                              |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
| [8](/weeks/week-8.html)   | Tue, Sep 10       | Linear Regression                                              | [📖](https://learning.monash.edu/mod/resource/view.php?id=3115252)                               | [📋](https://learning.monash.edu/pluginfile.php/4105703/mod_resource/content/1/lec-8.html#/title-slide)                                                                  | [📝](https://learning.monash.edu/mod/quiz/view.php?id=3114969)  | 📕 Camm Chapter 8.1-8.6, 8.8                 |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
| [9](/weeks/week-9.html)   | Tue, Sep 17       | Time Series Analysis and Forecasting                           | [📖](https://learning.monash.edu/pluginfile.php/4123810/mod_resource/content/2/lab-9.html)       | [📋](https://learning.monash.edu/pluginfile.php/4124063/mod_resource/content/1/lec-9.html#/title-slide)                                                                  | [📝](https://learning.monash.edu/mod/quiz/view.php?id=3133248)  | 📕 Camm Chapter 9                            |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
| Semester Break            | Sep 23 - Sep 27   | Mid semester break                                             |                                                                                                  |                                                                                                                                                                          |                                                                 |                                              |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
| [10](/weeks/week-10.html) | Tue, Oct 1        | Predictive Analytics: Classification (Binary Outcome Variable) | [📖](https://learning.monash.edu/pluginfile.php/4202858/mod_resource/content/3/lab-10.html)      | [📋](https://learning.monash.edu/pluginfile.php/4206953/mod_resource/content/2/lec-10.html#/title-slide)                                                                 | [📝](https://learning.monash.edu/mod/quiz/view.php?id=3205507)  | 📕 Camm Chapter 11.1, 11.2, 11.3, 11.4, 11.5 |
|                           |                   |                                                                |                                                                                                  |                                                                                                                                                                          |                                                                 |                                              |
|                           |                   |                                                                | [\[qmd\]](https://learning.monash.edu/mod/folder/view.php?id=3205505)                            |                                                                                                                                                                          |                                                                 |                                              |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
| [11](/weeks/week-11.html) | Tue, Oct 8        | Predictive Analytics: Continuous Outcome Variable              | [📖](https://learning.monash.edu/pluginfile.php/4224494/mod_resource/content/1/lab-11.html)      | [📋](https://learning.monash.edu/pluginfile.php/4234540/mod_resource/content/1/lec-11.html#/title-slide)                                                                 | No QUIZ                                                         | 📕 Camm Chapter 10.1, 10.2, 10.3, 10.4, 10.5 |
|                           |                   |                                                                |                                                                                                  |                                                                                                                                                                          |                                                                 |                                              |
|                           |                   |                                                                | [\[qmd\]](https://learning.monash.edu/mod/folder/view.php?id=3223664)                            |                                                                                                                                                                          |                                                                 |                                              |
|                           |                   |                                                                |                                                                                                  |                                                                                                                                                                          |                                                                 |                                              |
|                           |                   |                                                                | [Tutorial solution released early](https://learning.monash.edu/mod/resource/view.php?id=3223666) |                                                                                                                                                                          |                                                                 |                                              |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
| [12](/weeks/week-12.html) | Tue, Oct 15       | Revision/Presentation                                          | [📖](https://learning.monash.edu/pluginfile.php/4234054/mod_resource/content/1/lab-12.html)      |                                                                                                                                                                          | No QUIZ                                                         |                                              |
|                           |                   |                                                                |                                                                                                  |                                                                                                                                                                          |                                                                 |                                              |
|                           |                   |                                                                | [\[qmd\]](https://learning.monash.edu/mod/folder/view.php?id=3232329)                            |                                                                                                                                                                          |                                                                 |                                              |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
|                           | *Sun, Oct 18*     | *Group Assignment Submission Deadline*                         |                                                                                                  |                                                                                                                                                                          |                                                                 |                                              |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+
| *SWOT*                    | *Oct 21 - Oct 25* | *SWOT*                                                         |                                                                                                  |                                                                                                                                                                          |                                                                 |                                              |
+---------------------------+-------------------+----------------------------------------------------------------+--------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+----------------------------------------------+

: {tbl-colwidths="\[10, 20, 40,10, 10, 10, 30\]"}

```{r echo = FALSE}

knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project | Quiz |
|------|------|-------|:-------:|:------:|:---:|:----------------------------------------------------------------------------------------------------------:|:---:|:----:|:-------:|:----:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |  ✅  |   📂    |  📝  |
