---
title: "An Introduction to Modeling Uncertainty"
subtitle: "ETF2121: Week 5"
author: "Dr. Joan Tan"
footer:  "Week 5 - Uncertainty"
logo: "images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: true
    transition: fade
    slide-number: true
    incremental: false
editor: visual
execute:
  freeze: auto
---

```{r setup}
#| include: false

library(countdown)
library(ggplot2)

knitr::opts_chunk$set(
  fig.width = 8,
  fig.asp = 0.618,
  fig.retina = 3,
  dpi = 300,
  out.width = "80%",
  fig.align = "center"
)

knitr::asis_output("\n\n---\n\n")

options(scipen = 100)
```

## Announcements

-   Group assignment will be posted tomorrow, due on Week 11.
-   Individual assignment 1 due next week!

## Random Variables

::: {.callout-note title="Definition"}
A **random variable** is a variable whose value is the outcome of a random phenomenon.
:::

**Types of Random Variables**

-   Discrete random variables
-   Continuous random variables

**Importance in Business**

-   understanding and predicting business outcomes
-   decision-making under uncertainty
-   risk management/assessment

## Discrete Random Variables

::: {.callout-note title="Definition"}
A **discrete random variable** is a random variable that can take on a finite or infinite sequence of values.
:::

-   Characteristics: countable, finite or infinite

::: content-center
| Random Experiment                           | Random Variable (x)                    | Possible Values for the Random Variable                       |
|---------------------------------------------|----------------------------------------|---------------------------------------------------------------|
| Flip a coin                                 | Outcome of the coin flip               | 1 if heads; 0 if tails                                        |
| Roll a die                                  | Number of dots showing on the die      | 1, 2, 3, 4, 5, 6                                              |
| Contact five customers                      | Number of customers who place an order | 0, 1, 2, 3, 4, 5                                              |
| Operate a health care clinic for one day    | Number of patients arriving            | 0, 1, 2, 3, and so on                                         |
| Offer a customer the choice of two products | Choice made by the customer            | 0 if none; 1 if product A is chosen; 2 if product B is chosen |
:::

::: notes
1.  Flip a coin: The random variable here represents the outcome of a single coin flip. It can either be heads (1) or tails (0).

2.  Roll a die: The random variable represents the number of dots showing on the top face of a die after a roll. Possible values range from 1 to 6.

3.  Contact five customers: The random variable represents the number of customers out of five who place an order. Possible values are any whole number from 0 to 5.

4.  Operate a health care clinic for one day: The random variable represents the number of patients who arrive at the clinic in a single day. The number of patients can be any non-negative integer.

5.  Offer a customer the choice of two products: The random variable represents the choice made by the customer. If the customer chooses neither product, the value is 0; if they choose product A, the value is 1; if they choose product B, the value is 2.
:::

## Continuous Random Variables

::: {.callout-note title="Definition"}
A **continuous random variable** is a random variable that can take on any value in an interval.
:::

-   Characteristics: uncountable, infinite

::: content-center
| Scenario                                           | Random Variable (x)                         | Possible Values for the Random Variable |
|----------------------------------------------------|---------------------------------------------|-----------------------------------------|
| Customer visits a web page                         | Time spent on the web page (minutes)        | x ≥ 0                                   |
| Fill a soft drink can (max capacity = 12.1 ounces) | Amount of drink in the can (ounces)         | 0 ≤ x ≤ 12.1                            |
| Test a new chemical process                        | Temperature for the desired reaction (°F)   | 150 ≤ x ≤ 212                           |
| Invest \$10,000 in the stock market                | Value of the investment after one year (\$) | x ≥ 0                                   |
:::

::: notes
-   Customer visits a web page: The random variable represents the time a customer spends on the web page, measured in minutes. This time can be any non-negative number (x ≥ 0).

-   Fill a soft drink can (max capacity = 12.1 ounces): The random variable represents the amount of drink in the can, measured in ounces. This amount can range from 0 to 12.1 ounces (0 ≤ x ≤ 12.1).

-   Test a new chemical process: The random variable represents the temperature at which the desired reaction occurs, measured in degrees Fahrenheit. This temperature can range from 150°F to 212°F (150 ≤ x ≤ 212).

-   Invest \$10,000 in the stock market: The random variable represents the value of the investment after one year, measured in dollars. This value can be any non-negative number (x ≥ 0).
:::

## Discrete Probability Distributions

**Type of Discrete Probability Distributions:** - Uniform Distribution - Binomial Distribution - Poisson Distribution

## Business Examples (Discrete)

1.  **Uniform Distribution**
    -   **Scenario**: Rolling a fair die.
    -   **Random Variable (x)**: Number of dots showing on the die.
    -   **Possible Values**: 1, 2, 3, 4, 5, 6.
2.  **Binomial Distribution**
    -   **Scenario**: Number of successful sales calls out of a fixed number of attempts.
    -   **Random Variable (x)**: Number of successful calls.
    -   **Possible Values**: 0, 1, 2, ..., n.

------------------------------------------------------------------------

3.  **Poisson Distribution**
    -   **Scenario**: Number of customer arrivals at a store within an hour.
    -   **Random Variable (x)**: Number of arrivals.
    -   **Possible Values**: 0, 1, 2, 3, ...

## Continuous Probability Distributions

**Type of Continuous Probability Distributions:** - Triangular Distribution - Uniform Distribution - Normal Distribution - Exponential Distribution

## Business Examples (Continuous)

1.  **Triangular Distribution**
    -   **Scenario**: Estimating the duration of a project.
    -   **Random Variable (x)**: Duration of the project.
    -   **Possible Values**: Minimum, most likely, maximum.
2.  **Normal Distribution**
    -   **Scenario**: Distribution of human heights.
    -   **Random Variable (x)**: Height of a person.
    -   **Possible Values**: Any real number.

------------------------------------------------------------------------

3.  **Exponential Distribution**
    -   **Scenario**: Time between customer arrivals at a store.
    -   **Random Variable (x)**: Time between arrivals.
    -   **Possible Values**: Any positive real number.
